### ISSUE TITLE
Error a la primera instrucció de compilació.

### ISSUE THREAD

**Issue by axeelbl** [OS-GEI-IGUALADA-2223/HandsOn#4]
A la primera instrucció de compilació, es  "gcc -o pokemon pokemon.c", i hauria de ser "gcc -o main main.c", perquè només hem creat l'arxiu main en aquest moment i encara no hem creat l'arxiu pokemon.c

**Comment by JordiMateoUdL** [comment]
Genial! Bona feina! Gràcies pel comentari. Ara afegeixo la correcció al repo.
