### ISSUE TITLE
Sergio Lorca Mulero

### ISSUE THREAD

**Issue by espitijungle** [OS-GEI-IGUALADA-2223/HandsOn#6]
void test_crear_pokemon() {
    Pokemon pikachu = create_pokemon(25, "Pikachu", 0.4, 6.0);
    if (p.pokemon_id != 25 || strcmp(p.name, "Pikachu") != 0 ||
        p.height != 0.4 || p.weight != 6.0) {
        printf("ERROR: test_crear_pokemon NO SUPERAT. Dades incorrectes.\n");
    } else {
        printf("Test de test_crear_pokemon passat amb èxit.\n");
    }
    destroy_pokemon(pikachu);
}

Quan fas aquest test posa p.pokemon,p.name,... Hauria de ser pikachu.pokemon,pikachu.name,...

**Comment by JordiMateoUdL** [comment]
Perfecte. En breus estarà solucionat! Bona feina!
